### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by k8117** [ronreiter/bruteforce-seed#4]
Traceback (most recent call last):
  File "G:\brute force seeed\bruteforce.py", line 4, in <module>
    from bip_utils import Bip39MnemonicValidator
ModuleNotFoundError: No module named 'bip_utils'

**Comment by k8117** [comment]
Traceback (most recent call last):
  File "G:\brute force seeed\bruteforce.py", line 4, in <module>
    from bip_utils import Bip39MnemonicValidator
ModuleNotFoundError: No module named 'bip_utils'

**Comment by YashvirGaming** [comment]
@k8117  

### **the only working is this one 
checks on 6 blockchain and API** 
DM on [Telegram or Discord](https://t.me/dmyashvirgamingbot)

https://github.com/ronreiter/bruteforce-seed/assets/64865096/2dce4c67-6288-4fdd-877a-6868a9e99475
